name: Ping Render App Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:        # Allow manual runs too

permissions:
  contents: write  # Needed for commit & push

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ping Render app and log response
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" https://messenger-ybyw.onrender.com/)
          echo "$(date '+%Y-%m-%d %H:%M:%S') - Ping status: $status" >> messengerlog.txt

      - name: Commit and push messengerlog.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add messengerlog.txt
          git commit -m "Update messengerlog.txt with ping status" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
